### ISSUE TITLE
Fails to build on 32-bit architectures (e.g., armv7, i386, powerpc)

### ISSUE THREAD

**Issue by jbeich** [alex-courtis/way-displays#185]
Regressed by #164. From [error log](https://pkg-status.freebsd.org/beefy21/data/141i386-default/e7b7ad617ba1/logs/errors/way-displays-1.12.0.log):
```c
$ export CFLAGS=-m32
$ gmake || make
[...]
lib/col/src/itable.c:317:60: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
  317 |                 bufp += snprintf(bufp, len - (bufp - buf), "%lu = %s\n", *k, *v ? (char*)*v : "(null)");
      |                                                             ~~~          ^~
      |                                                             %llu
```

**Comment by alex-courtis** [comment]
Thanks for letting me know, I'll get back to you on the weekend

**Comment by alex-courtis** [comment]
32-bit builds should now be successful and functional: https://github.com/alex-courtis/way-displays/releases/tag/1.12.1

This was a great opportunity to add 32-bit tests and many stricter checks.

As usual, many thanks for your patience @jbeich

**Comment by jbeich** [comment]
I confirm, 1.12.1 builds fine on FreeBSD i386.
